# https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.8"

services:
  db:
    # https://hub.docker.com/_/postgres  15.4-alpineを採用
    image: postgres:15.4-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "./api/tmp/db:/var/lib/postgresql/data"

  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    # 仮想環境で起動したRailsは、localhostのipアドレス「127.0.0.1」でアクセスできないため、仮想環境外部からアクセスできるように、localhostのipアドレス「127.0.0.1」を「0.0.0.0」にバインド
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"
      APP_URL: "http://localhost:$API_PORT"
    volumes:
      - "./api:/$WORKDIR"
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"